version: "3.5"
services:

  gateway:
    build: servers/gateway
    container_name: john-gateway
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:                             
      - servers/gateway/.env # NEED TO BE SETUP
    networks:
      - john-net





  # API





  # APP
  sample-ai:
    build: clients/john
    container_name: john-sample-ai
    restart: always
    environment:
      - VITE_BASENAME=app
      - VITE_APP_NAME=sample-ai
    env_file:                            
      - clients/john/.env # NEED TO BE SETUP
    # ports:
    #   - 3100:5173
    networks:
      - john-net





  # AUTH
  authentication:
    build: servers/authentication
    container_name: john-authentication
    restart: always
    ports:
      - 8100:8100
    env_file:                             
      - servers/authentication/.env # NEED TO BE SETUP
    networks:
      - john-net
    depends_on:
      - mongodb





  # DATABASE
  mongodb:
    image: "mongo:latest"
    container_name: john-mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - db/.env # NEED TO BE SETUP
    volumes:
      - dbdata:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - john-net



networks:
  john-net:



volumes:
  dbdata:
    name: john-dbdata